CREATE OR REPLACE FUNCTION MAKEASALE(
  P_SNO STAFF.STAFF_NO%TYPE,
  P_SCODE STOCK.STOCK_CODE%TYPE,
  P_QTY integer) RETURN CHAR AS
  V_INSTOCK integer;
  V_SNAME STAFF.STAFF_NAME%TYPE;
BEGIN
  SELECT STAFF_NAME INTO V_SNAME FROM STAFF WHERE STAFF_NO = P_SNO;
  SELECT QUANTITYINSTOCK INTO V_INSTOCK 
  FROM STOCK WHERE STOCK_CODE = P_SCODE;
  IF (V_INSTOCK >= P_QTY) THEN
    INSERT INTO SALE (STAFF_NO, STOCK_CODE, QUANTITY, SALEDATE)
    VALUES (P_SNO, P_SCODE, P_QTY, SYSDATE);
    UPDATE STOCK
      SET QUANTITYINSTOCK = QUANTITYINSTOCK - P_QTY
    WHERE STOCK_CODE = P_SCODE;
    COMMIT;
    RETURN 'Y';
  ELSE
    RETURN 'N';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
   ROLLBACK;
   RAISE;
END MAKEASALE;
    
