create or replace
TRIGGER CORDERLINE_BIR
BEFORE INSERT ON CORDERLINE
FOR EACH ROW
DECLARE
NOT_ENOUGH_STOCK EXCEPTION;
QTY INTEGER;
BEGIN
SELECT STOCK_LEVEL - :NEW.QUANTITYREQUIRED INTO QTY FROM STOCK WHERE STOCK_CODE = :NEW.STOCK_CODE;
IF QTY < 0 THEN
  RAISE NOT_ENOUGH_STOCK;
END IF;
EXCEPTION
WHEN NOT_ENOUGH_STOCK THEN
  RAISE_APPLICATION_ERROR(-20003,'Not enough stock');
END;