SET SERVEROUTPUT ON

DECLARE
C_LN CLIENT.CLNAME%TYPE := '&Last_Name';
C_ID integer;

BEGIN
SELECT clientid INTO C_ID FROM CLIENT WHERE clname LIKE C_LN;
DBMS_OUTPUT.PUT_LINE('We found the id: '||C_ID);
EXCEPTION
  WHEN OTHERS THEN
   DBMS_OUTPUT.PUT_LINE(SQLCODE||' '||SQLERRM);
END;
